nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin:
            - '^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$'
            - '%env(CORS_ALLOW_ORIGIN)%'
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'Origin', 'X-Requested-With']
        expose_headers: ['Link', 'X-API-VERSION']
        max_age: 3600
    paths:
        '^/': null
