api-key-controllers:
    resource:
        path: ../src/ApiKey/Transport/Controller/Api/
        namespace: App\ApiKey\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

role-controllers:
    resource:
        path: ../src/Role/Transport/Controller/Api/
        namespace: App\Role\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

tool-controllers:
    resource:
        path: ../src/Tool/Transport/Controller/Api/
        namespace: App\Tool\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

user-controllers:
    resource:
        path: ../src/User/Transport/Controller/Api/
        namespace: App\User\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

company-controllers:
    resource:
        path: ../src/Company/Transport/Controller/Api/
        namespace: App\Company\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

candidate-controllers:
    resource:
        path: ../src/Candidate/Transport/Controller/Api/
        namespace: App\Candidate\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

job-controllers:
    resource:
        path: ../src/JobApplication/Transport/Controller/Api/
        namespace: App\JobApplication\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

job-offer-controllers:
    resource:
        path: ../src/JobOffer/Transport/Controller/Api/
        namespace: App\JobOffer\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

offer-controllers:
    resource:
        path: ../src/Offer/Transport/Controller/Api/
        namespace: App\Offer\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

media-controllers:
    resource:
        path: ../src/Media/Transport/Controller/Api/
        namespace: App\Media\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

notification-controllers:
    resource:
        path: ../src/Notification/Transport/Controller/Api/
        namespace: App\Notification\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

chat-controllers:
    resource:
        path: ../src/Chat/Transport/Controller/Api/
        namespace: App\Chat\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

resume-controllers:
    resource:
        path: ../src/Resume/Transport/Controller/Api/
        namespace: App\Resume\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json
