api-key-controllers:
    resource:
        path: ../src/ApiKey/Transport/Controller/Api/
        namespace: App\ApiKey\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

role-controllers:
    resource:
        path: ../src/Role/Transport/Controller/Api/
        namespace: App\Role\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

tool-controllers:
    resource:
        path: ../src/Tool/Transport/Controller/Api/
        namespace: App\Tool\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

user-controllers:
    resource:
        path: ../src/User/Transport/Controller/Api/
        namespace: App\User\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

company-controllers:
    resource:
        path: ../src/Company/Transport/Controller/Api/
        namespace: App\Company\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

recruit-controllers:
    resource:
        path: ../src/Recruit/Transport/Controller/Api/
        namespace: App\Recruit\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

media-controllers:
    resource:
        path: ../src/Media/Transport/Controller/Api/
        namespace: App\Media\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

notification-controllers:
    resource:
        path: ../src/Notification/Transport/Controller/Api/
        namespace: App\Notification\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

chat-controllers:
    resource:
        path: ../src/Chat/Transport/Controller/Api/
        namespace: App\Chat\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

blog-controllers:
    resource:
        path: ../src/Blog/Transport/Controller/Api/
        namespace: App\Blog\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json

task-controllers:
    resource:
        path: ../src/Task/Transport/Controller/Api/
        namespace: App\Task\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json


calendar-controllers:
    resource:
        path: ../src/Calendar/Transport/Controller/Api/
        namespace: App\Calendar\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json
