# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'en'
    read_endpoint_cache.default_ttl: '%env(int:REST_READ_CACHE_DEFAULT_TTL)%'
    read_endpoint_cache.ttls:
        job_offer: '%env(int:REST_READ_CACHE_JOB_OFFER_TTL)%'
        job_application: '%env(int:REST_READ_CACHE_JOB_APPLICATION_TTL)%'
        user: '%env(int:REST_READ_CACHE_USER_TTL)%'
        task: '%env(int:REST_READ_CACHE_TASK_TTL)%'
        blog: '%env(int:REST_READ_CACHE_BLOG_TTL)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $projectDir: '%kernel.project_dir%'
            $environment: '%kernel.environment%'
            $locale: '%locale%'
            $databaseHealthHistoryDays: '%env(int:DATABASE_HEALTH_HISTORY_DAYS)%'
            $databaseLogLoginHistoryDays: '%env(int:DATABASE_LOG_LOGIN_HISTORY_DAYS)%'
            $databaseLogRequestHistoryDays: '%env(int:DATABASE_LOG_REQUEST_HISTORY_DAYS)%'
            $messengerMessagesHistoryDays: '%env(int:MESSENGER_MESSAGES_HISTORY_DAYS)%'
            $elasticNumberOfShards: '%env(int:ELASTICSEARCH_NUMBER_OF_SHARDS)%'
            $elasticNumberOfReplicas: '%env(int:ELASTICSEARCH_NUMBER_OF_REPLICAS)%'
            $lockUserOnLoginFailureAttempts: '%env(int:LOCK_USER_ON_LOGIN_FAILURE_ATTEMPTS)%'
            $mediaStoragePath: '%env(resolve:MEDIA_STORAGE_PATH)%'
            $mediaStoragePublicPrefix: '%env(resolve:MEDIA_STORAGE_PUBLIC_PREFIX)%'
    _instanceof:
        App\General\Application\Rest\Interfaces\RestResourceInterface:
            tags: [ 'app.rest.resource', 'app.stopwatch' ]
        App\General\Application\Rest\Interfaces\RestSmallResourceInterface:
            tags: [ 'app.rest.resource', 'app.stopwatch' ]
        App\General\Application\Rest\Interfaces\BaseRestResourceInterface:
            calls:
                - setValidator: ['@validator']
        AutoMapperPlus\MapperInterface:
            tags: [ 'app.stopwatch' ]
        Symfony\Component\EventDispatcher\EventSubscriberInterface:
            tags: [ 'app.stopwatch' ]
        Symfony\Component\HttpKernel\Controller\ValueResolverInterface:
            tags: [ 'app.stopwatch' ]
        App\General\Application\Utils\Interfaces\MailSenderInterface:
            calls:
                - setMailerService: [ '@App\General\Domain\Service\Interfaces\MailerServiceInterface', '%env(resolve:APP_SENDER_EMAIL)%', '%env(resolve:APP_ERROR_RECEIVER_EMAIL)%', '%env(int:APP_EMAIL_NOTIFICATION_ABOUT_ERROR)%']
                - setTwig: ['@twig']

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/*/Infrastructure/DataFixtures/'
            - '../src/DependencyInjection/'
            - '../src/*/Domain/Entity/'
            - '../src/*/Transport/EventListener/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class

    App\Tool\Application\Service\Rest\ReadEndpointCache:
        arguments:
            $cache: '@app.rest_read_cache'
            $defaultTtl: '%read_endpoint_cache.default_ttl%'
            $ttls: '%read_endpoint_cache.ttls%'

    App\General\Transport\ValueResolver\EntityValueResolver:
        tags:
            - { name: controller.argument_value_resolver, priority: 150 }

    App\Log\Application\Service\RequestLoggerService:
        arguments:
            $sensitiveProperties: '%env(json:REQUEST_LOG_SENSITIVE_PROPERTIES)%'

    App\General\Transport\EventSubscriber\RequestLogSubscriber:
        arguments:
            $ignoredRoutes: '%env(json:REQUEST_LOG_IGNORED_ROUTES)%'

    App\ApiKey\Application\Service\Crypt\OpenSslCryptApiKeyService:
        arguments:
            $apiKeyTokenHashAlgo: '%env(API_KEY_TOKEN_HASH_ALGO)%'

    App\ApiKey\Application\Security\Provider\ApiKeyUserProvider:
        arguments:
            $apiKeyTokenOpenSslEncrypt: '%env(bool:API_KEY_TOKEN_OPEN_SSL_ENCRYPT)%'
            $apiKeyTokenHashAlgo: '%env(API_KEY_TOKEN_HASH_ALGO)%'

    App\Tool\Domain\Service\Crypt\OpenSslCryptService:
        arguments:
            $algorithm: '%env(OPEN_SSL_ALGORITHM)%'
            $openSslKey: '%env(OPEN_SSL_KEY)%'

    App\General\Infrastructure\Messenger\Strategy\FailedRetry:
        arguments:
            $isRetryable: '%env(bool:MESSENGER_FAILED_IS_RETRYABLE)%'
            $retryWaitingTime: '%env(int:MESSENGER_FAILED_RETRY_WAITING_TIME)%'

    App\General\Domain\Service\Interfaces\ElasticsearchServiceInterface:
        class: App\General\Infrastructure\Service\ElasticsearchService
        arguments:
            $host: '%env(ELASTICSEARCH_HOST)%'
            $username: '%env(ELASTICSEARCH_USERNAME)%'
            $password: '%env(ELASTICSEARCH_PASSWORD)%'
        #lazy: true

    app.serializer.normalizer.object.external_message:
        class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
        autoconfigure: false
        arguments:
            $nameConverter: '@serializer.name_converter.camel_case_to_snake_case'

    app.serializer.denormalizer.array.external_message:
        class: Symfony\Component\Serializer\Normalizer\ArrayDenormalizer
        autoconfigure: false

    app.serializer.normalizer.date_time.external_message:
        class: Symfony\Component\Serializer\Normalizer\DateTimeNormalizer
        autoconfigure: false
        arguments:
            - { datetime_format: 'Y-m-d H:i:s' }

    app.serializer.encoder.json.external_message:
        class: Symfony\Component\Serializer\Encoder\JsonEncoder
        autoconfigure: false

    app.serializer.external_message:
        class: Symfony\Component\Serializer\Serializer
        autoconfigure: false
        arguments:
            $normalizers:
                - '@app.serializer.normalizer.date_time.external_message'
                - '@app.serializer.normalizer.object.external_message'
                - '@app.serializer.denormalizer.array.external_message'
            $encoders:
                - '@app.serializer.encoder.json.external_message'

    App\Tool\Transport\Serializer\ExternalMessageSerializer:
        arguments:
            $serializer: '@app.serializer.external_message'


    App\Chat\Application\Service\Realtime\ChatRealtimePublisher:
        arguments:
            $hub: '@?mercure.hub.default'

    App\Chat\Application\Service\Realtime\Interfaces\ChatRealtimePublisherInterface:
        alias: App\Chat\Application\Service\Realtime\ChatRealtimePublisher

    App\Notification\Application\Service\Channel\EmailNotification:
        arguments:
            $senderEmail: '%env(resolve:APP_SENDER_EMAIL)%'

    App\Notification\Application\Service\Channel\SmsNotification:
        arguments:
            $texter: '@?texter'
            $fromNumber: '%env(SMS_FROM_NUMBER)%'

    App\Notification\Application\Service\Channel\PushNotification:
        arguments:
            $hub: '@?mercure.hub.default'



    App\Media\Application\Service\Interfaces\MediaStorageServiceInterface:
        class: App\Media\Infrastructure\Service\MediaStorageService

    App\Configuration\Application\Resource\Interfaces\ConfigurationResourceInterface:
        class: App\Configuration\Application\Resource\ConfigurationResource

    App\Configuration\Domain\Repository\Interfaces\ConfigurationRepositoryInterface:
        class: App\Configuration\Infrastructure\Repository\ConfigurationRepository

    App\Notification\Application\Service\Interfaces\NotificationServiceInterface:
        class: App\Notification\Application\Service\NotificationService

    App\Notification\Application\Service\Interfaces\NotificationChannelServiceInterface:
        class: App\Notification\Application\Service\NotificationChannelService

    App\Notification\Application\Service\Interfaces\NotificationOrchestratorInterface:
        class: App\Notification\Application\Service\NotificationOrchestrator

    App\Notification\Application\Service\Channel\Interfaces\EmailNotificationInterface:
        alias: App\Notification\Application\Service\Channel\EmailNotification

    App\Notification\Application\Service\Channel\Interfaces\PushNotificationInterface:
        alias: App\Notification\Application\Service\Channel\PushNotification

    App\Notification\Application\Service\Channel\Interfaces\SmsNotificationInterface:
        alias: App\Notification\Application\Service\Channel\SmsNotification


    App\User\Application\Security\Permission\Interfaces\CompanyPermissionMatrixInterface:
        class: App\User\Application\Security\Permission\CompanyPermissionMatrix

    App\Task\Application\Service\Interfaces\TaskAccessServiceInterface:
        class: App\Task\Application\Service\TaskAccessService

    App\Quiz\Application\Service\Interfaces\QuizAccessServiceInterface:
        class: App\Quiz\Application\Service\QuizAccessService

    App\Task\Application\Resource\Interfaces\TaskResourceInterface:
        class: App\Task\Application\Resource\TaskResource

    App\Task\Application\Resource\Interfaces\ProjectResourceInterface:
        class: App\Task\Application\Resource\ProjectResource

    App\Task\Application\Resource\Interfaces\SprintResourceInterface:
        class: App\Task\Application\Resource\SprintResource

    App\Task\Application\Resource\Interfaces\TaskRequestResourceInterface:
        class: App\Task\Application\Resource\TaskRequestResource

    App\Calendar\Application\Resource\Interfaces\EventResourceInterface:
        class: App\Calendar\Application\Resource\EventResource

    App\Calendar\Domain\Repository\Interfaces\EventRepositoryInterface:
        class: App\Calendar\Infrastructure\Repository\EventRepository

    App\Task\Domain\Repository\Interfaces\SprintRepositoryInterface:
        class: App\Task\Infrastructure\Repository\SprintRepository

    App\Quiz\Application\Resource\Interfaces\QuizResourceInterface:
        class: App\Quiz\Application\Resource\QuizResource

    App\Quiz\Domain\Repository\Interfaces\QuizRepositoryInterface:
        class: App\Quiz\Infrastructure\Repository\QuizRepository

    App\Blog\Application\Resource\Interfaces\BlogPostResourceInterface:
        class: App\Blog\Application\Resource\BlogPostResource

    App\Blog\Application\Resource\Interfaces\BlogTagResourceInterface:
        class: App\Blog\Application\Resource\BlogTagResource

    App\Blog\Application\Resource\Interfaces\BlogCommentResourceInterface:
        class: App\Blog\Application\Resource\BlogCommentResource

    App\Blog\Application\Resource\Interfaces\BlogPostLinkResourceInterface:
        class: App\Blog\Application\Resource\BlogPostLinkResource

    App\Blog\Domain\Repository\Interfaces\BlogPostRepositoryInterface:
        class: App\Blog\Infrastructure\Repository\BlogPostRepository

    App\Blog\Domain\Repository\Interfaces\BlogTagRepositoryInterface:
        class: App\Blog\Infrastructure\Repository\BlogTagRepository

    App\Blog\Domain\Repository\Interfaces\BlogCommentRepositoryInterface:
        class: App\Blog\Infrastructure\Repository\BlogCommentRepository

    App\Blog\Domain\Repository\Interfaces\BlogPostLinkRepositoryInterface:
        class: App\Blog\Infrastructure\Repository\BlogPostLinkRepository

when@dev:
    services:
        _defaults:
            autowire: true
            autoconfigure: true

        App\ApiKey\Infrastructure\DataFixtures\:
            resource: '../src/ApiKey/Infrastructure/DataFixtures/*'

        App\Role\Infrastructure\DataFixtures\:
            resource: '../src/Role/Infrastructure/DataFixtures/*'

        App\User\Infrastructure\DataFixtures\:
            resource: '../src/User/Infrastructure/DataFixtures/*'

        App\Company\Infrastructure\DataFixtures\:
            resource: '../src/Company/Infrastructure/DataFixtures/*'

        App\Blog\Infrastructure\DataFixtures\:
            resource: '../src/Blog/Infrastructure/DataFixtures/*'

        App\Recruit\Infrastructure\DataFixtures\:
            resource: '../src/Recruit/Infrastructure/DataFixtures/*'

        App\Task\Infrastructure\DataFixtures\:
            resource: '../src/Task/Infrastructure/DataFixtures/*'

        App\Calendar\Infrastructure\DataFixtures\:
            resource: '../src/Calendar/Infrastructure/DataFixtures/*'
        App\Tests\TestCase\:
            resource: '../tests/TestCase/*'

        App\Tests\Utils\:
            resource: '../tests/Utils/*'

        ProxyManager\Factory\AccessInterceptorValueHolderFactory:
            class: ProxyManager\Factory\AccessInterceptorValueHolderFactory

        doctrine.dbal.default_connection.stopwatch:
            class: Doctrine\DBAL\Connection
            decorates: doctrine.dbal.default_connection
            factory: [ '@App\General\Application\Decorator\StopwatchDecorator', decorate ]
            arguments: [ '@doctrine.dbal.default_connection.stopwatch.inner' ]

        symfony.component.serializer.stopwatch:
            class: Symfony\Component\Serializer\Serializer
            decorates: serializer
            factory: [ '@App\General\Application\Decorator\StopwatchDecorator', decorate ]
            arguments: [ '@symfony.component.serializer.stopwatch.inner' ]

when@test:
    services:
        _defaults:
            autowire: true
            autoconfigure: true
            public: true

        App\ApiKey\Infrastructure\DataFixtures\:
            resource: '../src/ApiKey/Infrastructure/DataFixtures/*'

        App\Role\Infrastructure\DataFixtures\:
            resource: '../src/Role/Infrastructure/DataFixtures/*'

        App\User\Infrastructure\DataFixtures\:
            resource: '../src/User/Infrastructure/DataFixtures/*'

        App\Recruit\Infrastructure\DataFixtures\:
            resource: '../src/Candidate/Infrastructure/DataFixtures/*'

        App\Company\Infrastructure\DataFixtures\:
            resource: '../src/Company/Infrastructure/DataFixtures/*'

        App\Blog\Infrastructure\DataFixtures\:
            resource: '../src/Blog/Infrastructure/DataFixtures/*'

        App\Tests\TestCase\:
            resource: '../tests/TestCase/*'

        App\Tests\Utils\:
            resource: '../tests/Utils/*'

        App\Calendar\Infrastructure\DataFixtures\:
            resource: '../src/Calendar/Infrastructure/DataFixtures/*'
